### ISSUE TITLE
MediaWiki >1.27 Compatibility

### ISSUE THREAD

**Issue by pfabri** [Daniel-KM/Scripto#7]
Dear Daniel,

It seems that the standard login protocol has changed following the release of MediaWiki 1.27 and up. A MediaWiki `cookie prefix` is now required for compatibility. This has already been integrated into the original Omeka branch of the plugin, but is missing from your more feature-rich version. 

Would you consider merging it into your branch (if it is possible, which I'm not sure about)?

Thank you,
Peter

**Comment by Daniel-KM** [comment]
Hi Peter,

I work mainly on Omeka S now, so I just maintain my plugins for Omeka Classic, without any improvements (except some of them for some institutions). 

Anyway, I merged the last commits of the original Scripto, so now it should work with MediaWiki 1.27 and up.

Sincerely,

Daniel Berthereau

**Comment by pfabri** [comment]
Hi Daniel,

Thank you for the merge! 

So is OmekaS going to overtake Omeka classic entirely? It was suggested on Omeka.org, that both branches would continue to be developed side-by-side. Is this not the case? I'm asking because I'm just setting up a large archive from scratch and it would be nice to go with a system with long term support. But with Omeka S still being in Beta and with only a fraction of the plugins available I deliberately chose to stick with the classic version. But I fear that updating from one to the other at a later point will likely be problematic especially with customisations. My site must launch by mid-October, so I cannot really wait for S to be released.

**Comment by Daniel-KM** [comment]
Hi Peter,

There are at least two sites with Omeka S already. See http://bibnum.explore.univ-psl.fr (in French, sorry, but this is a big French university with multiple attached independant schools).

The Omeka team wants to keep the two branches, because Omeka is primarly designed for heritage collections and the sites should be working for a long time, so it is a good reason. Nevertheless, Omeka S can already do all what Omeka Classic do and only specific plugins miss. 

There are numerous features in Omeka S that are not present in Omeka Classic, in particular the Semantic part (rdf), the "simplicity" of development (based on Zend 3 and composer), the modernity of the code, the resource templates, the management of vocabularies, the management of sites, the versality of items and medias, etc. And there are already a lot of plugins that were upgraded, the main one (see https://daniel-km.github.io/UpgradeToOmekaS/), and there will be newer in the next months. 

So, now, despite the aim of the Omeka team, I always recommand to use Omeka S and I think that Omeka Classic will no longer really evolve, even if the maintenance will be provided (and this is very important). Omeka S will be maintained too!

For my part, I'm currently upgrading some Omeka Classic sites that will be published once the Omeka S will be stable (in October normally). If you want such services, ask me...

Sincerely,

**Comment by pfabri** [comment]
Dear Daniel,

Thank you for your thorough answer. I really do appreciate your work and the time you dedicate to answering everybody's questions on all the support forums. I don't know how you do it.

My site will primarily be hosting text documents (in jpeg format displayed with UV), most of which were typed up on an old typewriter. These can be OCR'd with adequate accuracy, unless they are heavily annotated (some of them are). The rest of the documents are handwritten and I will need to use the community to crowd-source transcriptions. I therefore rely heavily on your fork of Scripto.

I am very grateful for you offer. Seeing how soon I will have to launch the site, I think I better stick to Omeka Classic for now, and as soon as all the plugins are available on Omeka S, I'll approach you to pick your brain about upgrading from Classic to S. 

Many-many thanks in advance!
Peter
